FROM nvcr.io/nvidia/pytorch:25.11-py3

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu130

RUN git clone https://github.com/comfyanonymous/ComfyUI.git /app/ComfyUI

RUN pip install -r /app/ComfyUI/requirements.txt

EXPOSE 8188

CMD ["python", "/app/ComfyUI/main.py", "--listen", "0.0.0.0", "--port", "8188"]